name: Run Friends Script

on:
  push:
    branches:
      - "*"

jobs:
  run-friends-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "20"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: npm install

      - name: Run friends.js with no sandbox
        run: node friends.js --no-sandbox
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
