name: Run Friends Script

on:
  push:
    branches:
      - "*"

jobs:
  run-friends-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "20"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: npm install

      - name: Run friends.js with no sandbox
        run: node friends.js --no-sandbox
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"
      - name: 同步 repo
        run: |
          bash -c 'if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "工作树无变更，跳过提交步骤..."
          else
            echo "提交文件中..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore(generated): GitHub Actions Bot 提交的记录"
            git log -3 --oneline
            echo "推送更新中..."
            git push
          fi'