name: Generate Friend Link Images

on:
  push:
    paths:
      - 'friends.json'  # 触发条件：当 friends.json 更新时运行

jobs:
  generate-images:
    runs-on: ubuntu-20.04  # 使用 Ubuntu 20.04 环境
    permissions:
      contents: write  # 授予写权限以提交生成的图片

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 修正：使用正确的公共操作格式

      - name: Set up Python
        uses: actions/setup-python@v2  # 修正：使用正确的公共操作格式
        with:
          python-version: '3.8'  # 指定 Python 版本

      - name: Install dependencies
        run: |
          pip install Pillow requests

      - name: Generate images
        run: |
          python generate_images.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images/*
          git commit -m "Update friend link images" || echo "No changes to commit"
          git push